/* SMIT LEGAL FINAL MASTER CONTROLLER
   Consolidates admin editing, add-service controls, file queue, order sync and Excel reporting.
*/
(function(){
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function isAdmin(){return !!$('#adminPanel')&&getComputedStyle($('#adminPanel')).display!=='none'}
function d(){try{return typeof read==='function'?read():JSON.parse(localStorage.getItem('smitLegalAdminV6')||'{}')}catch{return {services:[],tracking:[]}}}
function w(x){if(typeof write==='function')write(x);else localStorage.setItem('smitLegalAdminV6',JSON.stringify(x));window.dispatchEvent(new CustomEvent('smit-admin-data-updated'))}
function opts(){try{return JSON.parse(localStorage.getItem('smitSubOptionsV1')||'{}')||{}}catch{return {}}}
function saveOpts(x){localStorage.setItem('smitSubOptionsV1',JSON.stringify(x));window.dispatchEvent(new CustomEvent('smit-suboptions-updated'))}
function addStyles(){if($('#smit-final-master-style'))return;const s=document.createElement('style');s.id='smit-final-master-style';s.textContent=`
#smitServiceManager{margin:12px 0;padding:14px;border:1px solid #d9dee8;border-radius:14px;background:var(--card,#fff)}
.smit-manager-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;align-items:end}.smit-manager-row label{font-size:13px;font-weight:700}.smit-manager-row input,.smit-manager-row textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #cbd2dd;border-radius:9px}.smit-final-folder{margin-top:10px;padding:10px;border-radius:10px;border:1px solid #e2e5ec}.smit-final-file-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:6px}
`;
document.head.appendChild(s)}
function serviceManager(){if(!isAdmin()||$('#smitServiceManager'))return;const box=document.createElement('div');box.id='smitServiceManager';box.innerHTML=`<h3 style="margin:0 0 10px">➕ Service Management</h3><div class="smit-manager-row"><label>Main Service Name<input id="smNewMainName" placeholder="e.g. PAN Services"></label><label>Description<input id="smNewMainDesc" placeholder="Short guidance"></label><button type="button" class="primary-btn" id="smAddMain">＋ Add Main Service</button></div><div id="smSubManager" style="margin-top:12px"></div>`;const anchor=$('#adminServiceSearchWrap')||$('#adminServices');anchor?.parentNode?.insertBefore(box,anchor);$('#smAddMain').onclick=()=>{const name=$('#smNewMainName').value.trim();if(!name)return alert('Main Service name is required.');const x=d();x.services=x.services||[];x.services.push([name,$('#smNewMainDesc').value.trim(),[],'']);w(x);$('#smNewMainName').value='';$('#smNewMainDesc').value='';if(window.SmitFinalAdminFlow?.main)window.SmitFinalAdminFlow.main();else if(typeof renderAdmin==='function')renderAdmin();renderSubManager()};renderSubManager()}
function renderSubManager(){const box=$('#smSubManager');if(!box)return;const x=d(),services=x.services||[];box.innerHTML=`<div class="smit-manager-row"><label>Main Service<select id="smSubMain">${services.map((s,i)=>`<option value="${i}">${esc(s[0])}</option>`).join('')}</select></label><label>Sub-service Name<input id="smNewSubName" placeholder="e.g. New PAN"></label><label>Required Documents<input id="smNewSubDocs" placeholder="Aadhaar, photo..."></label><label>Guidance<input id="smNewSubGuide" placeholder="Suggestion / guidance"></label><label>Charge<input id="smNewSubCharge" type="number" min="0" value="0"></label><button type="button" class="secondary-btn" id="smAddSub">＋ Add Sub-service</button></div>`;$('#smAddSub').onclick=()=>{const i=Number($('#smSubMain').value),name=$('#smNewSubName').value.trim();if(!name)return alert('Sub-service name is required.');const cur=d();cur.services[i]=cur.services[i]||[name,'',[],''];cur.services[i][2]=cur.services[i][2]||[];cur.services[i][2].push([name,$('#smNewSubGuide').value.trim(),$('#smNewSubDocs').value.trim(),$('#smNewSubCharge').value.trim()]);w(cur);if(typeof renderAdmin==='function')renderAdmin();renderSubManager()}}
function addOptionControl(){const wrap=$('#adminServices');if(!wrap||$('#smAddOption'))return;const subName=$('#afSubName');if(!subName)return;const box=document.createElement('div');box.id='smAddOption';box.className='admin-flow-actions';box.innerHTML='<button type="button" class="secondary-btn">＋ Add Sub-option</button>';subName.closest('.admin-service')?.appendChild(box);box.querySelector('button').onclick=()=>{const svc=Number(wrap.querySelector('.admin-service')?.dataset.serviceIndex),subs=d().services?.[svc]?.[2]||[];const j=subs.findIndex(x=>x[0]===subName.value.trim());if(j<0)return alert('Save the Sub-service name first.');const a=opts(),key=svc+':'+j;a[key]=Array.isArray(a[key])?a[key]:[];a[key].push({name:'New Option',guidance:'',documents:'',governmentFee:0,serviceCharge:0});saveOpts(a);if(typeof renderAdmin==='function'){wrap.dataset.selectedService=String(svc);wrap.dataset.selectedSub=String(j);wrap.dataset.level='sub';renderAdmin()}}}
function afterRender(){if(!isAdmin())return;addStyles();serviceManager();renderSubManager();addOptionControl();document.querySelectorAll('#adminServices input,#adminServices textarea,#adminServices select').forEach(e=>{e.disabled=false;e.readOnly=false;e.removeAttribute('disabled');e.removeAttribute('readonly')});}
function wrapRender(){if(window.__smitRenderWrapped)return;const orig=window.renderAdmin;if(typeof orig==='function'){window.renderAdmin=function(){const r=orig.apply(this,arguments);setTimeout(afterRender,0);return r};window.__smitRenderWrapped=true}afterRender()}
async function syncOrders(){try{const orders=window.SmitOrders?.orders?.();if(!Array.isArray(orders))return;const key=JSON.stringify(orders);if(key===window.__smitLastOrders)return;window.__smitLastOrders=key;await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orders})})}catch(e){}}
function fileManagerEnhance(){const box=$('#smitFileManager');if(!box||box.dataset.finalEnhanced)return;box.dataset.finalEnhanced='1';const head=box.querySelector('h3');if(head){const b=document.createElement('button');b.type='button';b.className='secondary-btn';b.style.marginLeft='8px';b.textContent='📁 Completed Files';head.appendChild(b);b.onclick=async()=>{const list=$('#smitFileList');if(!list)return;const q=($('#smitFileSearch')?.value||'').trim();const date=$('#smitFileDate')?.value||'today';const r=await fetch('/api/files?status=completed&date='+encodeURIComponent(date)+(q?'&q='+encodeURIComponent(q):''));const j=await r.json();list.innerHTML=j.files.length?j.files.map(f=>`<div class="smit-master-row smit-completed"><div><b>${esc(f.updatedName||f.originalName)}</b><div class="smit-master-muted">${esc(f.phone||'')} · ${esc(f.orderId||'')} · Completed</div></div><a class="secondary-btn" href="${esc(f.url)}" target="_blank">Open</a></div>`).join(''):'<div class="smit-master-muted">No completed files found.</div>'}}
}
function addUpdatedButtons(){const list=$('#smitFileList');if(!list)return;[...list.querySelectorAll('.smit-pending')].forEach(row=>{if(row.querySelector('[data-upload-updated]'))return;const link=row.querySelector('a[href*="/files/pending/"]');if(!link)return;const id=decodeURIComponent(link.getAttribute('href').split('/').pop());const actions=row.querySelector('.smit-master-actions');if(!actions)return;const inp=document.createElement('input');inp.type='file';inp.accept='.pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.csv,.html,.htm';inp.hidden=true;const b=document.createElement('button');b.type='button';b.className='secondary-btn';b.dataset.uploadUpdated='1';b.textContent='↻ Upload Updated';b.onclick=()=>inp.click();inp.onchange=async()=>{if(!inp.files[0])return;const fd=new FormData();fd.append('file',inp.files[0]);const r=await fetch('/api/files/'+encodeURIComponent(id)+'/update',{method:'POST',body:fd});if(!r.ok)return alert('Updated file upload failed.');alert('Updated file saved in Completed Files.');row.remove()};actions.appendChild(inp);actions.appendChild(b)})}
setInterval(()=>{if(isAdmin()){wrapRender();fileManagerEnhance();addUpdatedButtons();syncOrders()}},1200);
window.addEventListener('smit-orders-updated',syncOrders);document.addEventListener('DOMContentLoaded',()=>{setTimeout(wrapRender,500);setTimeout(syncOrders,1500)});
})();
